# Generated by Django 4.2.5 on 2023-10-03 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='babyname',
            name='year',
            field=models.CharField(max_length=200),
        ),
    ]
