# Generated by Django 4.2.5 on 2023-10-03 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_alter_babyname_people_alter_babyname_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='babyname',
            name='rank',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
