# Generated by Django 4.2.5 on 2023-10-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='namestore',
            name='recommand1',
            field=models.CharField(default='Tommy', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='namestore',
            name='recommand2',
            field=models.CharField(default='Bob', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='namestore',
            name='recommand3',
            field=models.CharField(default='Timmy', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='namestore',
            name='recommand4',
            field=models.CharField(default='Jam', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='namestore',
            name='recommand5',
            field=models.CharField(default='Candy', max_length=50),
            preserve_default=False,
        ),
    ]
